version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: syncmate-postgres
    restart: always
    environment:
      POSTGRES_DB: syncmate
      POSTGRES_USER: catoff
      POSTGRES_PASSWORD: catoff
    ports:
      - "5432:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catoff -d syncmate" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network  # Add this line

  app:
    build: .
    container_name: syncmate-app
    depends_on:
      postgres:
        condition: service_healthy  # Wait for postgres to be healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: postgres
      DB_PORT: 5431
      DB_NAME: syncmate
      DB_USER: catoff
      DB_PASSWORD: catoff
    networks:
      - app-network  # Add this line

volumes:
  pgdata:
  mongodata:

networks:
  app-network:
    driver: bridge