spring:
  application:
    name: SyncMate

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#gcp:
#  storage:
#    bucket-name: ${GCP_BUCKET_NAME}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v3/api-docs
    operationsSorter: method
    tagsSorter: alpha
    groups-order: desc
    display-request-duration: true


jwt:
  secret: ${JWT_SECRET}
